# Generated by Django 3.1.7 on 2021-03-22 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.TextField(default='bitfinex', max_length=30)),
                ('exchange_email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('slug', 'exchange_email')},
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote', to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaiko_type', models.TextField(choices=[('SPOT', 'spot'), ('MARGIN', 'margin'), ('FUTURE', 'future')], default='SPOT')),
                ('size_round_precision', models.IntegerField(default=9)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('init_kwargs', models.TextField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('predict_timestamp', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('min_trade_amount', models.FloatField(default=0, help_text='Min trade size for the instrument, e.g. bitfinex BTCUSD = 0.00082, bitmex XBTUSD - 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_trade_amount', models.FloatField(default=0, help_text='Max trade size for the instrument, e.g. bitfinex BTCUSD = 0.00082, bitmex XBTUSD - 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('slippage_pct_position_increase', models.FloatField(default=0, help_text='Max diff between current price and target instrument execution price on position increase.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)])),
                ('slippage_pct_position_decrease', models.FloatField(default=0, help_text='Max diff between current price and target instrument execution price on position decrease.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)])),
                ('exchange_credentials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchangecredentials')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instrument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bot')),
            ],
        ),
    ]
