# Generated by Django 3.1.7 on 2021-03-25 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('slug', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters are allowed.')])),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(default='binance', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base', to='core.currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote', to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SPOT', 'SPOT'), ('MARGIN', 'MARGIN'), ('FUTURE', 'FUTURE')], default='SPOT', max_length=6)),
                ('size_round_precision', models.IntegerField(default=9)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parameters', models.JSONField(default=dict)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchange')),
            ],
            options={
                'verbose_name_plural': 'ExchangeCredentials',
            },
        ),
        migrations.CreateModel(
            name='BotStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('equity', models.FloatField()),
                ('exposure', models.FloatField()),
                ('employed_capital', models.FloatField()),
                ('price_crypto', models.FloatField()),
                ('price_fair', models.FloatField()),
                ('price_forex', models.FloatField()),
                ('balance_base_borrowed', models.FloatField()),
                ('balance_quote_borrowed', models.FloatField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='exchange_credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exchangecredentials'),
        ),
        migrations.AddField(
            model_name='bot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instrument'),
        ),
    ]
