# Generated by Django 3.0.3 on 2020-03-24 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('min_trade_amount', models.FloatField(default=0, help_text='Min trade size for the instrument, e.g. bitfinex BTCUSD = 0.00082, bitmex XBTUSD - 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_trade_amount', models.FloatField(default=0, help_text='Max trade size for the instrument, e.g. bitfinex BTCUSD = 0.00082, bitmex XBTUSD - 1', validators=[django.core.validators.MinValueValidator(0)])),
                ('slippage_pct_position_increase', models.FloatField(default=0, help_text='Max diff between current price and target instrument execution price on position increase.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)])),
                ('slippage_pct_position_decrease', models.FloatField(default=0, help_text='Max diff between current price and target instrument execution price on position decrease.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='BotSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.FloatField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('timestamp_consolidator', models.IntegerField()),
                ('timestamp_real', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bot')),
            ],
        ),
        migrations.CreateModel(
            name='BotSizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('type', models.TextField(choices=[('FIXED', 'fixed'), ('PERCENT', 'percent'), ('KELLY', 'kelly')], default='fixed')),
                ('kwargs', models.TextField(default='{}')),
                ('is_short_allowed', models.BooleanField(default=False)),
                ('is_long_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.TextField(default='bitfinex', max_length=30)),
                ('exchange_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base', to='core.Currency')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote', to='core.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('SPOT', 'spot'), ('MARGIN', 'margin')], default='SPOT')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Exchange')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('init_kwargs', models.TextField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('TIME', 'time'), ('PERCENT', 'percent')], default='TIME')),
                ('kwargs', models.TextField()),
                ('update_timestamp', models.IntegerField(default=0)),
                ('parent_update_timestamp', models.IntegerField(default=0)),
                ('latest_bar_data', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Instrument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Consolidator')),
            ],
        ),
        migrations.CreateModel(
            name='BotTargetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_target_size', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-5), django.core.validators.MaxValueValidator(5)])),
                ('instrument_target_execution_price', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('data_feed_info', models.TextField(blank=True, default=None, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bot')),
                ('bot_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BotSignal')),
            ],
        ),
        migrations.CreateModel(
            name='BotPositionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_avg', models.FloatField(default=None)),
                ('size', models.FloatField(default=None)),
                ('timestamp', models.FloatField(default=-1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bot')),
                ('bot_target_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BotTargetState')),
            ],
        ),
        migrations.CreateModel(
            name='BotPerformanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('exposure', models.FloatField()),
                ('unrealized_pnl', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Bot')),
                ('bot_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BotSignal')),
            ],
        ),
        migrations.CreateModel(
            name='BotOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('MARKET', 'market')], default='market')),
                ('price_avg', models.FloatField(default=None)),
                ('size', models.FloatField(default=None)),
                ('timestamp', models.FloatField(default=-1)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Bot')),
                ('bot_target_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BotTargetState')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='data_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Consolidator'),
        ),
        migrations.AddField(
            model_name='bot',
            name='exchange_credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ExchangeCredentials'),
        ),
        migrations.AddField(
            model_name='bot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Instrument'),
        ),
        migrations.AddField(
            model_name='bot',
            name='sizing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BotSizing'),
        ),
    ]
