# Generated by Django 3.1.7 on 2021-03-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='account',
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner'),
        ),
    ]
