# Generated by Django 3.1.7 on 2021-03-25 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210325_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecredentials',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.owner'),
            preserve_default=False,
        ),
    ]
