# Generated by Django 3.0.4 on 2020-03-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bot_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together={('slug', 'exchange_email')},
        ),
    ]
