# Generated by Django 3.0.4 on 2020-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200330_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='precision',
            field=models.FloatField(default=1e-09),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.TextField(choices=[('SPOT', 'spot'), ('MARGIN', 'margin'), ('FUTURE', 'future')], default='SPOT'),
        ),
    ]
