# Generated by Django 3.1.7 on 2021-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210325_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='amount_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='price_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
