# Generated by Django 3.0.4 on 2020-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200330_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='precision',
        ),
        migrations.AddField(
            model_name='instrument',
            name='size_round_precision',
            field=models.IntegerField(default=9),
        ),
    ]
