# Generated by Django 3.1.7 on 2021-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210325_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='size_round_precision',
        ),
        migrations.AddField(
            model_name='instrument',
            name='order_amount_max',
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name='instrument',
            name='order_amount_min',
            field=models.FloatField(default=10),
        ),
    ]
