# Generated by Django 3.0.4 on 2020-03-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200330_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='kaiko_type',
        ),
    ]
