# Generated by Django 3.1.7 on 2021-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210330_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='balance_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='balance_snapshot_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
