# Generated by Django 2.2.10 on 2020-04-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200330_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMlConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(help_text='Model JobLib dump file', upload_to='')),
                ('fn_tasks', models.TextField(help_text='JobManager fn_tasks JSON object')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='ml_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.BotMlConfig'),
        ),
    ]
