# Generated by Django 3.1.7 on 2021-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210407_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecredentials',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
