# Generated by Django 3.1.7 on 2021-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210407_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
