# Generated by Django 2.2.10 on 2020-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200417_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='predict_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
