# Generated by Django 3.1.7 on 2021-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210407_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangecredentials',
            options={'ordering': ['order_id', 'name'], 'verbose_name_plural': 'ExchangeCredentials'},
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
