# Generated by Django 2.2.10 on 2020-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bot_predict_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmlconfig',
            name='last_update_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
