# Generated by Django 2.2.10 on 2020-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_botmlconfig_last_update_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmlconfig',
            name='file',
            field=models.FileField(help_text='Model JobLib dump file', upload_to='models'),
        ),
    ]
