# Generated by Django 3.1.7 on 2021-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210408_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
