# Generated by Django 3.1.7 on 2021-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_exchangecredentials_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='statistics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
