# Generated by Django 2.2.10 on 2020-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200418_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('type', models.TextField(choices=[('MAX_DRAWDOWN', 'max_drawdown')], default='fixed')),
                ('kwargs', models.TextField(default='{}')),
            ],
        ),
        migrations.AddField(
            model_name='botmlconfig',
            name='rows_count',
            field=models.TextField(default=-1, help_text='Minimal amount of rows to be fetched to calculate features'),
        ),
        migrations.AddField(
            model_name='bot',
            name='risk_models',
            field=models.ManyToManyField(blank=True, null=True, to='core.Risk'),
        ),
    ]
