# Generated by Django 2.2.10 on 2020-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200511_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmlconfig',
            name='rows_count',
            field=models.IntegerField(default=-1, help_text='Minimal amount of rows to be fetched to calculate features'),
        ),
    ]
