# Generated by Django 3.1.7 on 2021-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exchangecredentials_statistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['order_id', 'name']},
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='ignore_spot_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='owner',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
