# Generated by Django 2.2.10 on 2020-05-12 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200511_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottargetstate',
            name='instrument_target_exposure',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-3.5), django.core.validators.MaxValueValidator(3.5)]),
        ),
        migrations.AlterField(
            model_name='bottargetstate',
            name='instrument_target_size',
            field=models.FloatField(default=0.0),
        ),
    ]
