# Generated by Django 3.1.7 on 2021-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210413_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecredentials',
            name='ignore_spot_balance',
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='account_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('CROSS_MARGIN', 'Cross Margin'), ('ISOLATED_MARGIN', 'Isolated Margin'), ('FUTURES', 'Futures')], default='CROSS_MARGIN', max_length=15),
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='ignore_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
