# Generated by Django 3.1.7 on 2021-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210414_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecredentials',
            name='ignore_balance',
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
