# Generated by Django 3.1.7 on 2021-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210415_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangecredentials',
            name='account_type',
            field=models.CharField(choices=[('SPOT', 'Spot'), ('CROSS_MARGIN', 'Cross Margin'), ('ISOLATED_MARGIN', 'Isolated Margin'), ('USDT_M_FUTURES', 'USDT-M Futures'), ('COIN_M_FUTURES', 'COIN-M Futures')], default='CROSS_MARGIN', max_length=15),
        ),
    ]
