# Generated by Django 3.1.7 on 2021-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210415_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='ignore_balance',
            field=models.BooleanField(default=False),
        ),
    ]
