# Generated by Django 3.1.7 on 2021-04-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='exchange_credentials',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='instrument',
        ),
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner'),
        ),
    ]
