# Generated by Django 3.1.7 on 2021-05-04 14:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210430_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangecredentials',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='bot',
            name='config',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
