# Generated by Django 3.1.7 on 2021-05-13 14:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210504_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='account_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='config',
            field=models.JSONField(default=dict, encoder=core.models.CustomDjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='exchangecredentials',
            name='statistics',
            field=models.JSONField(blank=True, encoder=core.models.CustomDjangoJSONEncoder, null=True),
        ),
    ]
