# Generated by Django 3.1.7 on 2021-07-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210513_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='ignore_datapipes',
            field=models.BooleanField(db_index=True, default=False, help_text='Disables a collecting data for the account'),
        ),
    ]
