# Generated by Django 3.1.7 on 2022-03-31 18:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_exchangecredentials_ignore_datapipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='balance_snapshot_clean',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangecredentials',
            name='statistics_clean',
            field=models.JSONField(blank=True, encoder=core.models.CustomDjangoJSONEncoder, null=True),
        )
    ]
