# Generated by Django 3.1.7 on 2023-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220331_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        )
    ]
