# Generated by Django 3.1.7 on 2023-02-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230207_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingstatus',
            old_name='is_allowed',
            new_name='is_trading_allowed',
        ),
    ]
