# Generated by Django 3.1.7 on 2023-03-29 10:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230207_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangecredentials',
            name='fallback_since',
            field=models.DateTimeField(default=core.models.fallback_since_default, help_text='Fallback since date for trades datapipe'),
        )
    ]
