name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade "pip<20"
        pip install -r requirements.txt
        mkdir _req_install
        cp install_github.sh _req_install/
        cp requirements.github _req_install/
        cd _req_install
        chmod 0755 install_github.sh
        export GITHUB_TOKEN=${{ secrets.RCDB_GITHUB_TOKEN }}
        /bin/bash install_github.sh requirements.github
        cd ..
    - name: Test with pytest
      run: |
        pytest
